### ISSUE TITLE
Windows 7 support? | 是否支持 Windows 7？

### ISSUE THREAD

**Issue by cwup** [lujjjh/iLyrics#2]
> The procedure entry point CreateDXGIFactory2 could not be located in the dynamic link library dxgi.dll.

Does it support Windows 7?

---

> 无法定位程序输入点CreateDXGIFactory2于动态连接库dxgi.dll。

是不支持 Windows 7 吗？

**Comment by lujjjh** [comment]
你好！

目前我只在 Windows 10 上测试过，使用的 API 理论上需要 Windows 8 或者更高版本。

[Windows 7 已经结束支持][1]，最新版的 iTunes 也仅支持 Windows 10，因此这个软件暂时没有支持 Windows 7 的计划。

[1]: https://docs.microsoft.com/en-us/lifecycle/products/windows-7

**Comment by lujjjh** [comment]
I'm closing this issue. If you have any further questions, please feel free to reopen it.

---

先关闭这个 issue 了，如果有任何问题，欢迎随时重新打开。
