### ISSUE TITLE
Link Error During Compile

### ISSUE THREAD

**Issue by silenuszhi** [lujjjh/iLyrics#5]
report error when compiling in vscode using powershell extension

"message"   note: LINK : fatal error LNK1181: cannot open input file 'dbgmodel.lib'

os  win10 21h2 x64
cargo 1.56.0 (4ed5d137b 2021-10-04)

**Comment by lujjjh** [comment]
Not sure what dbgmodel.lib is. But have you got Windows SDK installed?

**Comment by silenuszhi** [comment]
Nope. And after I install Windows SDK it works.
Just change the lyric font successfully, Thank u for ur awesome work.
