### ISSUE TITLE
關於歌詞沒有搜索到的情況

### ISSUE THREAD

**Issue by Danal-chen** [lujjjh/iLyrics#6]
您好，我在使用的時候當插件無法搜尋到歌詞的時候他會以上一首歌的歌詞繼續撥放
導致歌跟歌詞顯示的不一致，我想可能在搜索不到的情況需要清理歌詞

**Comment by lujjjh** [comment]
谢谢提供反馈，我在 [v0.0.10](https://github.com/lujjjh/iLyrics/releases/tag/v0.0.10) 中修复了这个 BUG。
